/**
 * Explicit sidebar for the OHS Player documentation.
 *
 * The order below is the site's information architecture and is deliberate,
 * so it is declared here rather than autogenerated from the directory tree.
 *
 * The spine is the reader's journey, not a taxonomy of document kinds:
 *
 *   Understand  ->  Run it  ->  Configure  ->  Extend  ->  Project
 *
 * Each audience enters at the same place and travels a different distance.
 * An evaluator stops after Understand. An implementor continues through
 * Configure and Extend. A contributor arrives at Project.
 *
 * Understand explains what each component offers; Run it sets them up. A
 * component's overview therefore sits in Understand and its setup guide in
 * Run it. One page per job, no page written twice.
 *
 * Reference Infrastructure is deliberately not in the component set. It is
 * deployment material rather than a component, so it opens Run it instead.
 *
 * Reserved positions, named but not yet published. Create each one when it
 * has content; do not publish an empty section to hold the slot.
 *
 *   See it working    the demo instance and downloadable builds, between
 *                     Understand and Run it
 *   Guides            cross-component recipes only
 *   Technical reference   lookup material, after Extend
 *
 * Directory paths do not have to mirror this order. Published slugs are
 * permanent, so a page keeps its URL when it moves between sections here.
 */

const sidebars = {
  playerReference: [
    "landing",
    {
      type: "category",
      label: "Understand",
      collapsible: false,
      items: [
        "concepts/what-ohs-player-is",
        "concepts/architecture",
        "concepts/how-player-uses-ohs-components",
        {
          type: "category",
          label: "The components",
          link: { type: "doc", id: "components/overview" },
          items: [
            "components/client-app/overview",
            "concepts/configuration-ig",
            "components/reference-backend/overview",
            "components/web-portal/overview",
            "components/reference-analytics/overview",
          ],
        },
        "concepts/configuration-model",
        "concepts/what-you-can-do-today",
        "prerequisites",
      ],
    },
    {
      type: "category",
      label: "Run it",
      collapsible: false,
      link: { type: "doc", id: "get-started" },
      items: [
        "components/reference-infrastructure/overview",
        "components/reference-backend/run",
        "components/web-portal/run",
        "components/client-app/run",
        "components/reference-analytics/run",
      ],
    },
    {
      type: "category",
      label: "Configure",
      collapsible: false,
      items: ["configure/screen-from-fhir-data"],
    },
    {
      type: "category",
      label: "Extend",
      collapsible: false,
      items: ["extend/decide", "extend/backend-extensions"],
    },
    {
      type: "category",
      label: "Project and community",
      collapsible: false,
      items: ["resources"],
    },
  ],

  /**
   * FHIR Foundations is the first documentation *section* beside the Player
   * journey: a set of repositories documented together with its own sidebar.
   * The name and structure follow the Foundation's official taxonomy at
   * https://ohs.foundation/projects, where "FHIR Foundations" is Pillar 01
   * and projects are labelled "Core Library" and "SDK". Future sections
   * (player-client-app, player-web, ...) follow the same mechanics — a
   * directory under docs/, a sidebar here, an entry point on the landing
   * page and in the SectionNav switcher.
   *
   * The pillar has two kinds of projects. *Core libraries* are unopinionated
   * building blocks usable in any Kotlin program, client or server. *SDKs*
   * are opinionated, application-facing toolkits built on them; today's SDKs
   * are client-side, and server-side SDKs would join as a sibling category.
   * Every repository follows the same skeleton — overview, get started, task
   * guides. Pillar-wide reference material (platform matrix, version
   * pairing) closes the sidebar.
   */
  fhirFoundations: [
    "fhir-foundations/overview",
    {
      type: "category",
      label: "Core libraries",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Kotlin FHIR",
          collapsible: false,
          link: { type: "doc", id: "fhir-foundations/kotlin-fhir/overview" },
          items: [
            "fhir-foundations/kotlin-fhir/get-started",
            "fhir-foundations/kotlin-fhir/working-with-resources",
            "fhir-foundations/kotlin-fhir/serialization",
            "fhir-foundations/kotlin-fhir/search-parameters",
          ],
        },
        {
          type: "category",
          label: "Kotlin FHIRPath",
          collapsible: false,
          link: { type: "doc", id: "fhir-foundations/kotlin-fhirpath/overview" },
          items: [
            "fhir-foundations/kotlin-fhirpath/get-started",
            "fhir-foundations/kotlin-fhirpath/evaluation-semantics",
            "fhir-foundations/kotlin-fhirpath/conformance",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SDKs",
      collapsible: false,
      items: [
        {
          type: "category",
          label: "Kotlin FHIR Engine",
          collapsible: false,
          link: {
            type: "doc",
            id: "fhir-foundations/kotlin-fhir-engine/overview",
          },
          items: [
            "fhir-foundations/kotlin-fhir-engine/get-started",
            "fhir-foundations/kotlin-fhir-engine/persist-and-search",
            "fhir-foundations/kotlin-fhir-engine/synchronization",
            "fhir-foundations/kotlin-fhir-engine/web-targets",
          ],
        },
        {
          type: "category",
          label: "Kotlin FHIR Data Capture",
          collapsible: false,
          link: {
            type: "doc",
            id: "fhir-foundations/kotlin-fhir-data-capture/overview",
          },
          items: [
            "fhir-foundations/kotlin-fhir-data-capture/get-started",
            "fhir-foundations/kotlin-fhir-data-capture/render-a-questionnaire",
            "fhir-foundations/kotlin-fhir-data-capture/customize-and-extend",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Across the stack",
      collapsible: false,
      items: [
        "fhir-foundations/platform-support",
        "fhir-foundations/versions",
      ],
    },
  ],
};

module.exports = sidebars;
