/**
 * Explicit sidebar for the OHS Player documentation.
 *
 * The order below is the site's information architecture and is deliberate,
 * so it is declared here rather than autogenerated from the directory tree.
 *
 * The spine is the reader's journey, not a taxonomy of document kinds:
 *
 *   Understand  ->  Run it  ->  Configure  ->  Extend  ->  Project
 *
 * Each audience enters at the same place and travels a different distance.
 * An evaluator stops after Understand. An implementor continues through
 * Configure and Extend. A contributor arrives at Project.
 *
 * Understand explains what each component offers; Run it sets them up. A
 * component's overview therefore sits in Understand and its setup guide in
 * Run it. One page per job, no page written twice.
 *
 * Reference Infrastructure is deliberately not in the component set. It is
 * deployment material rather than a component, so it opens Run it instead.
 *
 * Reserved positions, named but not yet published. Create each one when it
 * has content; do not publish an empty section to hold the slot.
 *
 *   See it working    the demo instance and downloadable builds, between
 *                     Understand and Run it
 *   Guides            cross-component recipes only
 *   Technical reference   lookup material, after Extend
 *
 * Directory paths do not have to mirror this order. Published slugs are
 * permanent, so a page keeps its URL when it moves between sections here.
 */

const sidebars = {
  playerReference: [
    "landing",
    {
      type: "category",
      label: "Understand",
      collapsible: false,
      items: [
        "concepts/what-ohs-player-is",
        "concepts/architecture",
        "concepts/how-player-uses-ohs-components",
        {
          type: "category",
          label: "The components",
          link: { type: "doc", id: "components/overview" },
          items: [
            "components/client-app/overview",
            "concepts/configuration-ig",
            "components/reference-backend/overview",
            "components/web-portal/overview",
            "components/reference-analytics/overview",
          ],
        },
        "concepts/configuration-model",
        "concepts/what-you-can-do-today",
        "prerequisites",
      ],
    },
    {
      type: "category",
      label: "Run it",
      collapsible: false,
      link: { type: "doc", id: "get-started" },
      items: [
        "components/reference-infrastructure/overview",
        "components/reference-backend/run",
        "components/web-portal/run",
        "components/client-app/run",
        "components/reference-analytics/run",
      ],
    },
    {
      type: "category",
      label: "Configure",
      collapsible: false,
      items: ["configure/screen-from-fhir-data"],
    },
    {
      type: "category",
      label: "Extend",
      collapsible: false,
      items: ["extend/decide", "extend/backend-extensions"],
    },
    {
      type: "category",
      label: "Project and community",
      collapsible: false,
      items: ["resources"],
    },
  ],
};

module.exports = sidebars;
