/**
 * Explicit sidebar for the OHS Player documentation.
 *
 * The order below is the site's information architecture and is deliberate,
 * so it is declared here rather than autogenerated from the directory tree.
 *
 * Reserved positions, named but not yet published. Create each one when it
 * has content; do not publish an empty section to hold the slot.
 *
 *   50  Guides                 cross-component recipes only
 *   80  Technical reference    lookup material
 *  100  Labs                   reproducible exercises
 *
 * Single-component procedures nest under their component in Reference
 * components. Adaptation does not nest: configuration lives in Configure
 * Player and code changes in Extend Player, whichever component they touch.
 */

const sidebars = {
  playerReference: [
    "landing",
    "get-started",
    "prerequisites",
    {
      type: "category",
      label: "Core concepts",
      collapsible: false,
      items: [
        "concepts/how-player-uses-ohs-components",
        "concepts/configuration-model",
      ],
    },
    {
      type: "category",
      label: "Reference components",
      collapsible: false,
      link: { type: "doc", id: "components/overview" },
      items: [
        {
          type: "category",
          label: "Client App",
          link: { type: "doc", id: "components/client-app/overview" },
          items: ["components/client-app/run"],
        },
        {
          type: "category",
          label: "Web Portal",
          link: { type: "doc", id: "components/web-portal/overview" },
          items: ["components/web-portal/run"],
        },
        "components/reference-backend/overview",
        "components/reference-infrastructure/overview",
        "components/reference-analytics/overview",
      ],
    },
    {
      type: "category",
      label: "Configure Player",
      collapsible: false,
      items: ["configure/screen-from-fhir-data"],
    },
    {
      type: "category",
      label: "Extend Player",
      collapsible: false,
      items: ["extend/decide", "extend/backend-extensions"],
    },
    "resources",
  ],
};

module.exports = sidebars;
